apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: c
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: c
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50