kind: ConfigMap
apiVersion: v1
metadata:
  name: direct-stress
  
data:
  stress.sh: |
    #!/bin/bash
    echo $message
    stress --timeout $1 --cpu $2 # test memory

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: a
  
data:
  stress.sh: |
    #!/bin/bash
    sleep 60; e

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: c
spec:
  # replicas: 1
  selector:
    matchLabels:
      app: c
  template:
    metadata:
      labels:
        app: c
    spec:

      containers:

        # - name: c2
        #   image: a
        #   command: ["bash"]
        #   args: ["300", "1"]
        #   env:
        #     - name: message
        #       value: "Hello World"
        #   volumeMounts:
        #     - name: a
        #       mountPath: stress/job1
        #   resources:
        #     requests:
        #       cpu: "0"
        #       memory: "7Mi"
        #     limits:
        #       cpu: "0"
        #       memory: "10Mi"

        - name: c1
          image: direct-stress
          command: ["bash"]
          args: ["300", "1"]
          env:
            - name: message
              value: "Hello World"
          volumeMounts:
            - name: direct-stress
              mountPath: stress/job1
          resources:
            requests:
              cpu: "2"
              memory: "7Mi"
            limits:
              cpu: "8"
              memory: "10Mi"


      volumes:
        - name: a
          configMap:
            name: a
        - name: direct-stress 
          configMap:
            name: direct-stress
      nodeSelector:
        kubernetes.io/role: agent
        kubernetes.io/hostname: vk
      tolerations:
        - key: "virtual-kubelet.io/provider"
          operator: "Equal"
          value: "mock"
          effect: "NoSchedule"
      restartPolicy: Always


# apiVersion: v1
# kind: Pod
# metadata:
#   name: cpu-stress
# spec:
#   containers:
#     - name: c1
#       image: direct-stress
#       command: ["bash"]
#       args: ["30", "2"]
#       env:
#         - name: message
#           value: "Hello World"
#       volumeMounts:
#         - name: direct-stress
#           mountPath: stress/job1
#       resources:
#         limits:
#           cpu: "2"
#           memory: 1Gi
#         requests:
#           cpu: "2"
#           memory: 1Gi
  


#   volumes:
#     - name: direct-stress 
#       configMap:
#         name: direct-stress

#   nodeSelector:
#     kubernetes.io/role: agent
#     kubernetes.io/hostname: vk
#   tolerations:
#     - key: "virtual-kubelet.io/provider"
#       value: "mock"
#       effect: "NoSchedule"
#   restartPolicy: Never