Pod:
  name: sample-exporter2
Service:
  - targetPort: 1124
  - targetPort: 1125
Nodes:
  worker: mylin-worker
Namespace: default
ServiceAccount: prometheus-k8s

#https://github.com/prometheus-operator/kube-prometheus/blob/main/docs/customizations/monitoring-additional-namespaces.md