kind: ConfigMap
apiVersion: v1
metadata:
  name: job1
  namespace: default
data:
  stress.sh: |
    #!/bin/bash
    # shifter --image="jlabtsai/stress:latest" --entrypoint
    # stress --cpu $cpu --timeout $timeout
    echo $workdir
    docker run -d --rm -e NUMBER=$NUMBER -e TIME=$TIME jlabtsai/stress:latest

---

apiVersion: v1
kind: Pod
metadata:
  name: stress
spec:
  containers:
    - name: job1
      image: job1
      command: ["/bin/bash", "-c"]
      args: ["bash $workdir/stress.sh >> $workdir/stdout 2>>$workdir/stderr"]
      env:
        - name: NUMBER
          value: "3"
        - name: TIME
          value: "60"
        - name: workdir
          value: "$HOME/stress/job1"

      volumeMounts:
        - name: job1
          mountPath: ~/stress/job1
        - name: pgid-1
          mountPath: ~/stress/job1/pgid

      resources:
        limits:
          cpu: "1"
          memory: 1Gi

    - name: job2
      image: job2
      command: ["/bin/bash", "-c"]
      args: ["bash $workdir/stress.sh >> $workdir/stdout 2>> $workdir/stderr"]
      env:
        - name: NUMBER
          value: "1"
        - name: TIME
          value: "40"
        - name: workdir
          value: "~/stress/job2"


      volumeMounts:
        - name: job1
          mountPath: ~/stress/job2
        - name: pgid-2
          mountPath: ~/stress/job2/pgid

      resources:
        limits:
          cpu: "1"
          memory: 1Gi


  volumes:
    - name: job1 
      configMap:
        name: job1
    - name: pgid-1
      emptyDir: {}
    - name: pgid-2
      emptyDir: {}
        
  nodeSelector:
    kubernetes.io/role: agent
  tolerations:
    - key: "virtual-kubelet.io/provider"
      value: "mock"
      effect: "NoSchedule"


---
