kind: ConfigMap
apiVersion: v1
metadata:
  name: job1
  namespace: default
data:
  stress.sh: |
    #!/bin/bash
    strss --cpu $cpu --timeout $timeout

---

apiVersion: v1
kind: Pod
metadata:
  name: stress
spec:
  containers:
    - name: job1
      image: job1
      command: ["/bin/bash", "-c"]
      args: ["bash ~/hostpipe/job1/stress.sh"]
      env:
        - name: fifo
          value: "true"
        - name: cpu
          value: "4"
        - name: timeout
          value: 60s

      volumeMounts:
        - name: job1
          mountPath: ~/hostpipe/job1

      resources:
        limits:
          cpu: "1"
          memory: 1Gi

    - name: job2
      image: job2
      command: ["/bin/bash", "-c"]
      args: ["bash ~/hostpipe/job2/stress.sh"]
      env:
        - name: fifo
          value: "true"
        - name: cpu
          value: "4"
        - name: timeout
          value: 60s

      volumeMounts:
        - name: job1
          mountPath: ~/hostpipe/job2

      resources:
        limits:
          cpu: "1"
          memory: 1Gi


  volumes:
    - name: job1 
      configMap:
        name: job1
        
  nodeSelector:
    kubernetes.io/role: agent
  tolerations:
    - key: "virtual-kubelet.io/provider"
      value: "mock"
      effect: "NoSchedule"


---
