kind: ConfigMap
apiVersion: v1
metadata:
  name: job1
  namespace: default
data:
  job1.job: |
    #!/bin/bash
    echo $message1
    echo $message2

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: support
  namespace: default
data:
  support.sh: |
    #!/bin/bash
    export message="hello world"

---

apiVersion: v1
kind: Pod
metadata:
  name: multijobs
spec:
  containers:
  # - name: support
  #   image: support
  #   command: ["/bin/bash"]
  #   volumeMounts:
  #   - name: support
  #     mountPath: ~/
  #   resources:
  #     limits:
  #       cpu: "1"
  #       memory: 1Gi
  #   env:
  #   - name: message
  #     value: "hello world"


  - name: job1
    image: job1
    command: ["/bin/bash"]
    env:
    - name: message1
      value: "hello world"
    - name: message2
      value: "my name is job1"

    volumeMounts:
    - name: job1
      mountPath: ~/
    resources:
      limits:
        cpu: "1"
        memory: 1Gi


  volumes:
    - name: job1 
      configMap:
        name: job1
    - name: support
      configMap:
        name: support

        
  nodeSelector:
    kubernetes.io/role: agent
  tolerations:
  - key: "virtual-kubelet.io/provider"
    value: "mock"
    effect: "NoSchedule"


---
