kind: ConfigMap
apiVersion: v1
metadata:
  name: job1
  namespace: default
data:
  stress.sh: |
    #!/bin/bash
    shifter --image="jlabtsai/stress:latest" 
    # stress --cpu $cpu --timeout $timeout
    # docker run -d --rm --name stress jlabtsai/stress:p1

---

apiVersion: v1
kind: Pod
metadata:
  name: stress
spec:
  containers:
    - name: job1
      image: job1
      command: ["/bin/bash", "-c"]
      args: ["bash ~/stress/job1/stress.sh >> ~/stress/job1/stdout 2>> ~/stress/job1/stderr"]
      env:
        - name: NUMBER
          value: "3"
        - name: TIME
          value: "60"

      volumeMounts:
        - name: job1
          mountPath: ~/stress/job1
        - name: pgid-1
          mountPath: ~/stress/job1/pgid

      resources:
        limits:
          cpu: "1"
          memory: 1Gi

    - name: job2
      image: job2
      command: ["/bin/bash", "-c"]
      args: ["bash ~/stress/job2/stress.sh >> ~/stress/job2/stdout 2>> ~/stress/job2/stderr"]
      env:
        - name: NUMBER
          value: "1"
        - name: TIME
          value: "40"

      volumeMounts:
        - name: job1
          mountPath: ~/stress/job2
        - name: pgid-2
          mountPath: ~/stress/job2/pgid

      resources:
        limits:
          cpu: "1"
          memory: 1Gi


  volumes:
    - name: job1 
      configMap:
        name: job1
    - name: pgid-1
      emptyDir: {}
    - name: pgid-2
      emptyDir: {}
        
  nodeSelector:
    kubernetes.io/role: agent
  tolerations:
    - key: "virtual-kubelet.io/provider"
      value: "mock"
      effect: "NoSchedule"


---
