kind: ConfigMap
apiVersion: v1
metadata:
  name: job1
  namespace: default
data:
  stress.sh: |
    #!/bin/bash
    stress --cpu $cpu --timeout $timeout

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: leader-pid-1
  namespace: default
data:
  job1.pgid: |
---

kind: ConfigMap
apiVersion: v1
metadata:
  name: leader-pid-2
  namespace: default
data:
  job2.pgid: |

---

apiVersion: v1
kind: Pod
metadata:
  name: stress
spec:
  containers:
    - name: job1
      image: job1
      command: ["/bin/bash", "-c"]
      args: ["bash ~/job1/stress.sh >> ~/job1/stdout 2>> ~/job1/stderr"]
      env:
        - name: fifo
          value: "false"
        - name: cpu
          value: "4"
        - name: timeout
          value: 60s

      volumeMounts:
        - name: job1
          mountPath: ~/job1
        - name: pgid-1
          mountPath: ~/job1/pgid

      resources:
        limits:
          cpu: "1"
          memory: 1Gi

    - name: job2
      image: job2
      command: ["/bin/bash", "-c"]
      args: ["bash ~/job2/stress.sh >> ~/job2/stdout 2>> ~/job2/stderr"]
      env:
        - name: fifo
          value: "false"
        - name: cpu
          value: "4"
        - name: timeout
          value: 60s

      volumeMounts:
        - name: job1
          mountPath: ~/job2
        - name: pgid-2
          mountPath: ~/job2/pgid

      resources:
        limits:
          cpu: "1"
          memory: 1Gi


  volumes:
    - name: job1 
      configMap:
        name: job1
    - name: pgid-1
      configMap:
        name: leader-pid-1
    - name: pgid-2
      configMap:
        name: leader-pid-2
        
  nodeSelector:
    kubernetes.io/role: agent
  tolerations:
    - key: "virtual-kubelet.io/provider"
      value: "mock"
      effect: "NoSchedule"


---
