kind: ConfigMap
apiVersion: v1
metadata:
  name: u1-j1
  namespace: default
data:
  u1-j1.job: |
     echo "hello world" > ~/u1-j1.txt
     sleep 2
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: u1-j2
  namespace: default
data :
  u1-j2.sh: |
     sleep 3
     sleep 4
     
---

kind: ConfigMap
apiVersion: v1
metadata:
  name: u2-j1
  namespace: default
data:
  u2-j1.sh: |
     sleep 5
     sleep 6

---

apiVersion: v1
kind: Pod
metadata:
  name: multijobs
spec:
  containers:
  - name: u1-j1
    image: u1-j1
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
    command: ["/bin/bash"]
    volumeMounts:
    - name: u1-j1
      # read from configmap
      mountPath: u1-j1

  - name : u1-j2
    image: u1-j2
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
    command: ["/bin/bash"]
    volumeMounts:
    - name: u1-j2
      mountPath: u1-j2


  - name: u2-j1
    image: u2-j1
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
    command: ["/bin/bash"]
    volumeMounts:
    - name: u2-j1
      mountPath: u2-j1 # path is auto generated by vk, the rule is: $HOME/podname/configmapname/volumename.

  volumes:
    - name: u1-j1
      configMap:
        name: u1-j1
    
    - name: u1-j2
      configMap:
        name: u1-j2

    - name: u2-j1
      configMap:
        name:  u2-j1

        
  nodeSelector:
    kubernetes.io/role: agent
  tolerations:
  - key: "virtual-kubelet.io/provider"
    value: "mock"
    effect: "NoSchedule"


---
