kind: ConfigMap
apiVersion: v1
metadata:
  name: direct-stress
  namespace: default
data:
  stress.sh: |
    #!/bin/bash
    echo $workdir
    stress --timeout $1 --cpu $2 --vm 1 --vm-bytes $3 # test memory

---

apiVersion: batch/v1
kind: Job
metadata:
  name: new-test
spec:
  template:
    spec:
      containers:
        - name: job1
          image: direct-stress
          command: ["bash"]
          args: ["30", "1", "10G"]
          volumeMounts:
            - name: direct-stress
              mountPath: stress/job1
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
        - name: job2
          image: direct-stress
          command: ["bash"]
          args: ["20", "1", "10G"]
          volumeMounts:
            - name: direct-stress
              mountPath: stress/job2
          resources:
            limits:
              cpu: "1"
              memory: 1Gi

      volumes:
        - name: direct-stress 
          configMap:
            name: direct-stress
        - name: test
          configMap:
            name: test
      nodeSelector:
        kubernetes.io/role: agent
        kubernetes.io/hostname: vk
      tolerations:
        - key: "virtual-kubelet.io/provider"
          value: "mock"
          effect: "NoSchedule"
      restartPolicy: Never
  backoffLimit: 4
  completions: 1