# https://kubernetes.io/docs/concepts/workloads/pods/
apiVersion: v1
kind: Pod
metadata:
  name: write-pod
spec:
  containers:
  - name: test-write-file
    image: fake
    command:
      - "ls -l .  > ~/test.txt && sleep 60"
    volumeMounts:
    - name: write-file
      mountPath: /workspaces/add-volume/test-run/write_files
  volumes:
    - name: write-file
      configMap:
        name:  myconfig-write-file

        
  nodeSelector:
    kubernetes.io/role: agent
  tolerations:
  - key: "virtual-kubelet.io/provider"
    value: "mock"
    effect: "NoSchedule"


---
