kind: ConfigMap
apiVersion: v1
metadata:
  name: direct-stress
  namespace: default
data:
  stress.sh: |
    #!/bin/bash
    echo $workdir
    # stress --timeout $TIME --vm 1 --vm-bytes 4G # test memory
    stress --timeout $TIME --cpu $NUMBER # test cpu

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: docker-stress
  namespace: default
data:
  stress.sh: |
    #!/bin/bash
    echo $workdir
    docker run -d --rm -e NUMBER=$NUMBER -e TIME=$TIME jlabtsai/stress:latest

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: shifter-stress
  namespace: default
data:
  stress.sh: |
    #!/bin/bash
    echo $workdir
    shifter --image="jlabtsai/stress:latest" --entrypoint

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: test
  namespace: default
data:
  test.sh: |
    #!/bin/bash
    echo $workdir


---

apiVersion: batch/v1
kind: Job
metadata:
  name: stress-job-direct
spec:
  template:
    spec:
      containers:
        - name: job1
          image: job1
          command: ["/bin/bash", "-c"]
          args: ["bash $workdir/stress.sh > $workdir/stdout 2>$workdir/stderr"]
          env:
            - name: NUMBER
              value: "4"
            - name: TIME
              value: "30"
            - name: workdir
              value: "~/stress/job1"
          volumeMounts:
            - name: direct-stress
              mountPath: ~/stress/job1
            - name: test
              mountPath: ~/stress/test
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
        - name: job2
          image: job2 
          command: ["/bin/bash", "-c"]
          args: ["bash $workdir/stress.sh > $workdir/stdout 2> $workdir/stderr"]
          env:
            - name: NUMBER
              value: "4"
            - name: TIME
              value: "100"
            - name: workdir
              value: "~/stress/job2"
          volumeMounts:
            - name: direct-stress
              mountPath: ~/stress/job2
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
      volumes:
        - name: direct-stress 
          configMap:
            name: direct-stress
        - name: test
          configMap:
            name: test
      nodeSelector:
        kubernetes.io/role: agent
        kubernetes.io/hostname: vk
      tolerations:
        - key: "virtual-kubelet.io/provider"
          value: "mock"
          effect: "NoSchedule"
      restartPolicy: Never
  backoffLimit: 4